/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNOS
 */
public class TelaPrecificacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaFornecedores
     */
    public TelaPrecificacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAzul = new javax.swing.JPanel();
        panelBranco = new javax.swing.JPanel();
        panelTabela = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        pesquisar = new java.awt.TextField();
        Aluguel = new javax.swing.JLabel();
        energia = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        agua = new javax.swing.JLabel();
        servico = new javax.swing.JLabel();
        barraEnergia = new javax.swing.JTextField();
        barraServico = new javax.swing.JTextField();
        barraAluguel = new javax.swing.JTextField();
        barraAgua = new javax.swing.JTextField();
        barraValor = new javax.swing.JTextField();
        cadastra = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        barraInternet = new javax.swing.JTextField();
        barraImposto = new javax.swing.JTextField();
        barraFrete = new javax.swing.JTextField();
        barraSalario = new javax.swing.JTextField();
        barraEmbalagem = new javax.swing.JTextField();
        impostos = new javax.swing.JLabel();
        internet = new javax.swing.JLabel();
        salario = new javax.swing.JLabel();
        frete = new javax.swing.JLabel();
        Embalagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAzul.setBackground(new java.awt.Color(16, 13, 40));

        panelBranco.setBackground(new java.awt.Color(255, 255, 255));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serviço", "Aluguel", "Energia", "Valor", "Agua", "Internet", "Impostos", "Frete", "Salario", "Embalagem"
            }
        ));
        panelTabela.setViewportView(tabela);

        javax.swing.GroupLayout panelBrancoLayout = new javax.swing.GroupLayout(panelBranco);
        panelBranco.setLayout(panelBrancoLayout);
        panelBrancoLayout.setHorizontalGroup(
            panelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBrancoLayout.setVerticalGroup(
            panelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pesquisar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        Aluguel.setBackground(new java.awt.Color(255, 255, 255));
        Aluguel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Aluguel.setForeground(new java.awt.Color(255, 255, 255));
        Aluguel.setText("Aluguel:");

        energia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        energia.setForeground(new java.awt.Color(255, 255, 255));
        energia.setText("Energia:");

        valor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        valor.setForeground(new java.awt.Color(255, 255, 255));
        valor.setText("Valor:");

        agua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agua.setForeground(new java.awt.Color(255, 255, 255));
        agua.setText("Agua:");

        servico.setBackground(new java.awt.Color(255, 255, 255));
        servico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        servico.setForeground(new java.awt.Color(255, 255, 255));
        servico.setText("Serviço:");

        barraEnergia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraEnergiaActionPerformed(evt);
            }
        });

        barraServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraServicoActionPerformed(evt);
            }
        });

        barraAluguel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        barraAgua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraAguaActionPerformed(evt);
            }
        });

        barraValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraValorActionPerformed(evt);
            }
        });

        cadastra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastra.setText("Cadastra");
        cadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        pdf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pdf.setText("Baixar PDF");

        barraInternet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraInternetActionPerformed(evt);
            }
        });

        barraImposto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraImposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraImpostoActionPerformed(evt);
            }
        });

        barraFrete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraFrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraFreteActionPerformed(evt);
            }
        });

        barraSalario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraSalarioActionPerformed(evt);
            }
        });

        barraEmbalagem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraEmbalagemActionPerformed(evt);
            }
        });

        impostos.setBackground(new java.awt.Color(255, 255, 255));
        impostos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        impostos.setForeground(new java.awt.Color(255, 255, 255));
        impostos.setText("Impostos:");

        internet.setBackground(new java.awt.Color(255, 255, 255));
        internet.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        internet.setForeground(new java.awt.Color(255, 255, 255));
        internet.setText("Internet:");

        salario.setBackground(new java.awt.Color(255, 255, 255));
        salario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        salario.setForeground(new java.awt.Color(255, 255, 255));
        salario.setText("Salario:");

        frete.setBackground(new java.awt.Color(255, 255, 255));
        frete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        frete.setForeground(new java.awt.Color(255, 255, 255));
        frete.setText("Frete:");

        Embalagem.setBackground(new java.awt.Color(255, 255, 255));
        Embalagem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Embalagem.setForeground(new java.awt.Color(255, 255, 255));
        Embalagem.setText("Embalagem:");

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addComponent(panelBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(servico)
                            .addComponent(Aluguel)
                            .addComponent(energia)
                            .addComponent(valor)
                            .addComponent(agua)
                            .addComponent(pdf))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAzulLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cadastra)
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzulLayout.createSequentialGroup()
                                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelAzulLayout.createSequentialGroup()
                                        .addComponent(barraAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Embalagem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(barraEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAzulLayout.createSequentialGroup()
                                        .addComponent(barraValor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(salario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(barraSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAzulLayout.createSequentialGroup()
                                        .addComponent(barraEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(frete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(barraFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAzulLayout.createSequentialGroup()
                                        .addComponent(barraAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(impostos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(barraImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAzulLayout.createSequentialGroup()
                                        .addComponent(barraServico, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(internet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(barraInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69))))))
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzulLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panelBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAzulLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(servico)
                                    .addComponent(barraServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barraInternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzulLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internet)))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(barraAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barraImposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(impostos))
                            .addComponent(Aluguel))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barraFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(energia)
                                .addComponent(barraEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(frete)))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor)
                            .addComponent(barraValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salario))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agua)
                            .addComponent(barraAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Embalagem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastra)
                            .addComponent(editar)
                            .addComponent(pdf))
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarActionPerformed

    private void barraServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraServicoActionPerformed

    private void barraEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraEnergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraEnergiaActionPerformed

    private void barraAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraAguaActionPerformed

    private void barraValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraValorActionPerformed

    private void cadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastraActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarActionPerformed

    private void barraInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraInternetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraInternetActionPerformed

    private void barraImpostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraImpostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraImpostoActionPerformed

    private void barraFreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraFreteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraFreteActionPerformed

    private void barraSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraSalarioActionPerformed

    private void barraEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraEmbalagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrecificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrecificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrecificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrecificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrecificacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aluguel;
    private javax.swing.JLabel Embalagem;
    private javax.swing.JLabel agua;
    private javax.swing.JTextField barraAgua;
    private javax.swing.JTextField barraAluguel;
    private javax.swing.JTextField barraEmbalagem;
    private javax.swing.JTextField barraEnergia;
    private javax.swing.JTextField barraFrete;
    private javax.swing.JTextField barraImposto;
    private javax.swing.JTextField barraInternet;
    private javax.swing.JTextField barraSalario;
    private javax.swing.JTextField barraServico;
    private javax.swing.JTextField barraValor;
    private javax.swing.JButton cadastra;
    private javax.swing.JButton editar;
    private javax.swing.JLabel energia;
    private javax.swing.JLabel frete;
    private javax.swing.JLabel impostos;
    private javax.swing.JLabel internet;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelBranco;
    private javax.swing.JScrollPane panelTabela;
    private javax.swing.JButton pdf;
    private java.awt.TextField pesquisar;
    private javax.swing.JLabel salario;
    private javax.swing.JLabel servico;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
