/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNOS
 */
public class TelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaFornecedores
     */
    public TelaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelazul = new javax.swing.JPanel();
        panelbranco = new javax.swing.JPanel();
        tabela = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        pesquisar = new java.awt.TextField();
        quantidade = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        validade = new javax.swing.JLabel();
        preco = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        barraquantidade = new javax.swing.JTextField();
        barradescricao = new javax.swing.JTextField();
        barrapreco = new javax.swing.JTextField();
        barracodigo = new javax.swing.JTextField();
        barravalidade = new javax.swing.JTextField();
        cadastra = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        barranome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelazul.setBackground(new java.awt.Color(16, 13, 40));

        panelbranco.setBackground(new java.awt.Color(255, 255, 255));

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Quantidade", "Descrição", "Validade", "Preço", "Codigó"
            }
        ));
        tabela.setViewportView(tabela2);

        javax.swing.GroupLayout panelbrancoLayout = new javax.swing.GroupLayout(panelbranco);
        panelbranco.setLayout(panelbrancoLayout);
        panelbrancoLayout.setHorizontalGroup(
            panelbrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbrancoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(tabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        panelbrancoLayout.setVerticalGroup(
            panelbrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbrancoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pesquisar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        quantidade.setBackground(new java.awt.Color(255, 255, 255));
        quantidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quantidade.setForeground(new java.awt.Color(255, 255, 255));
        quantidade.setText("Quantidade:");

        descricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 255, 255));
        descricao.setText("Descrição:");

        validade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        validade.setForeground(new java.awt.Color(255, 255, 255));
        validade.setText("Validade:");

        preco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        preco.setForeground(new java.awt.Color(255, 255, 255));
        preco.setText("Preço:");

        nome.setBackground(new java.awt.Color(255, 255, 255));
        nome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setText("Nome:");

        codigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        codigo.setForeground(new java.awt.Color(255, 255, 255));
        codigo.setText("codigó:");

        barraquantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraquantidadeActionPerformed(evt);
            }
        });

        barradescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        barrapreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        barracodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        barravalidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cadastra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastra.setText("Cadastra");

        editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editar.setText("Editar");

        pdf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pdf.setText("Baixar PDF");

        barranome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barranome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barranomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelazulLayout = new javax.swing.GroupLayout(panelazul);
        panelazul.setLayout(panelazulLayout);
        panelazulLayout.setHorizontalGroup(
            panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelazulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelazulLayout.createSequentialGroup()
                        .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelazulLayout.createSequentialGroup()
                        .addComponent(panelbranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelazulLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelazulLayout.createSequentialGroup()
                                        .addComponent(pdf)
                                        .addGap(54, 54, 54)
                                        .addComponent(editar)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelazulLayout.createSequentialGroup()
                                        .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(descricao)
                                                .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(preco)
                                                        .addComponent(codigo))
                                                    .addGroup(panelazulLayout.createSequentialGroup()
                                                        .addComponent(validade)
                                                        .addGap(14, 14, 14))))
                                            .addGroup(panelazulLayout.createSequentialGroup()
                                                .addComponent(quantidade)
                                                .addGap(4, 4, 4)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelazulLayout.createSequentialGroup()
                                        .addComponent(nome)
                                        .addGap(40, 40, 40)))
                                .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barrapreco, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barracodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barravalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barradescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barraquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barranome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 107, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelazulLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cadastra)
                                .addGap(19, 19, 19))))))
        );
        panelazulLayout.setVerticalGroup(
            panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelazulLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelazulLayout.createSequentialGroup()
                        .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(panelbranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelazulLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barranome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantidade))
                        .addGap(18, 18, 18)
                        .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barradescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricao))
                        .addGap(18, 18, 18)
                        .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barravalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validade))
                        .addGap(18, 18, 18)
                        .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barrapreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preco))
                        .addGap(20, 20, 20)
                        .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelazulLayout.createSequentialGroup()
                                .addComponent(barracodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(panelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pdf)
                                    .addComponent(editar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadastra))
                            .addComponent(codigo))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelazul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelazul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarActionPerformed

    private void barraquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraquantidadeActionPerformed

    private void barranomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barranomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barranomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barracodigo;
    private javax.swing.JTextField barradescricao;
    private javax.swing.JTextField barranome;
    private javax.swing.JTextField barrapreco;
    private javax.swing.JTextField barraquantidade;
    private javax.swing.JTextField barravalidade;
    private javax.swing.JButton cadastra;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel descricao;
    private javax.swing.JButton editar;
    private javax.swing.JLabel nome;
    private javax.swing.JPanel panelazul;
    private javax.swing.JPanel panelbranco;
    private javax.swing.JButton pdf;
    private java.awt.TextField pesquisar;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel quantidade;
    private javax.swing.JScrollPane tabela;
    private javax.swing.JTable tabela2;
    private javax.swing.JLabel validade;
    // End of variables declaration//GEN-END:variables
}
