/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNOS
 */
public class TelaFluxoDeCaixa extends javax.swing.JFrame {

    /**
     * Creates new form TelaFornecedores
     */
    public TelaFluxoDeCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAzul = new javax.swing.JPanel();
        panelBranco = new javax.swing.JPanel();
        panelTabela = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        pesquisar = new java.awt.TextField();
        produtos = new javax.swing.JLabel();
        origem = new javax.swing.JLabel();
        preco = new javax.swing.JLabel();
        pagamento = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        destino = new javax.swing.JLabel();
        barraOrigem = new javax.swing.JTextField();
        barraData = new javax.swing.JTextField();
        barraCnpj = new javax.swing.JTextField();
        barraPagamento = new javax.swing.JTextField();
        barraDestino = new javax.swing.JTextField();
        barraPreco = new javax.swing.JTextField();
        cadastra = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        barraCliente = new javax.swing.JTextField();
        cliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAzul.setBackground(new java.awt.Color(16, 13, 40));

        panelBranco.setBackground(new java.awt.Color(255, 255, 255));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Produtos", "Origem", "Preço", "Pagamento", "Destino", "Cliente"
            }
        ));
        panelTabela.setViewportView(tabela);

        javax.swing.GroupLayout panelBrancoLayout = new javax.swing.GroupLayout(panelBranco);
        panelBranco.setLayout(panelBrancoLayout);
        panelBrancoLayout.setHorizontalGroup(
            panelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrancoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        panelBrancoLayout.setVerticalGroup(
            panelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBrancoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pesquisar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        produtos.setBackground(new java.awt.Color(255, 255, 255));
        produtos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtos.setForeground(new java.awt.Color(255, 255, 255));
        produtos.setText("Produtos:");

        origem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        origem.setForeground(new java.awt.Color(255, 255, 255));
        origem.setText("Origem:");

        preco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        preco.setForeground(new java.awt.Color(255, 255, 255));
        preco.setText("Preço:");

        pagamento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pagamento.setForeground(new java.awt.Color(255, 255, 255));
        pagamento.setText("Pagamento:");

        data.setBackground(new java.awt.Color(255, 255, 255));
        data.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        data.setForeground(new java.awt.Color(255, 255, 255));
        data.setText("Data:");

        destino.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        destino.setForeground(new java.awt.Color(255, 255, 255));
        destino.setText("Destino:");

        barraOrigem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraOrigemActionPerformed(evt);
            }
        });

        barraData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraDataActionPerformed(evt);
            }
        });

        barraCnpj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        barraPagamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraPagamentoActionPerformed(evt);
            }
        });

        barraDestino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraDestinoActionPerformed(evt);
            }
        });

        barraPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraPrecoActionPerformed(evt);
            }
        });

        cadastra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastra.setText("Cadastra");
        cadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        pdf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pdf.setText("Baixar PDF");

        barraCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraClienteActionPerformed(evt);
            }
        });

        cliente.setBackground(new java.awt.Color(255, 255, 255));
        cliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cliente.setForeground(new java.awt.Color(255, 255, 255));
        cliente.setText("Cliente:");

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addComponent(panelBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(data)
                            .addComponent(produtos)
                            .addComponent(origem)
                            .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAzulLayout.createSequentialGroup()
                                    .addComponent(pdf)
                                    .addGap(31, 31, 31))
                                .addComponent(cliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(preco, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(pagamento)
                            .addComponent(destino))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAzulLayout.createSequentialGroup()
                                .addComponent(editar)
                                .addGap(87, 87, 87)
                                .addComponent(cadastra))
                            .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barraDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barraCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(barraOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraData, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 135, Short.MAX_VALUE))))
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzulLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panelBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(data)
                            .addComponent(barraData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barraCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(produtos))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origem)
                            .addComponent(barraOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preco)
                            .addComponent(barraPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pagamento)
                            .addComponent(barraPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destino)
                            .addComponent(barraDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cliente)
                            .addComponent(barraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pdf)
                            .addComponent(editar)
                            .addComponent(cadastra))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarActionPerformed

    private void barraDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraDataActionPerformed

    private void barraOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraOrigemActionPerformed

    private void barraPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPagamentoActionPerformed

    private void barraDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraDestinoActionPerformed

    private void barraPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPrecoActionPerformed

    private void cadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastraActionPerformed

    private void barraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraClienteActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFluxoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFluxoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFluxoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFluxoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFluxoDeCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraCliente;
    private javax.swing.JTextField barraCnpj;
    private javax.swing.JTextField barraData;
    private javax.swing.JTextField barraDestino;
    private javax.swing.JTextField barraOrigem;
    private javax.swing.JTextField barraPagamento;
    private javax.swing.JTextField barraPreco;
    private javax.swing.JButton cadastra;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel data;
    private javax.swing.JLabel destino;
    private javax.swing.JButton editar;
    private javax.swing.JLabel origem;
    private javax.swing.JLabel pagamento;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelBranco;
    private javax.swing.JScrollPane panelTabela;
    private javax.swing.JButton pdf;
    private java.awt.TextField pesquisar;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel produtos;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
